### ISSUE TITLE
Custom generators for certain constructors

### ISSUE THREAD

**Issue by sjakobi** [Lysxia/generic-random#14]
I would like to use custom generators for some constructors of a large AST. I've tried to use `Gen1_` for the `IntegerLit` constructor [here](https://github.com/dhall-lang/dhall-haskell/commit/b0e622adc144489d329f5b6b27df4f91560900c0), but it doesn't seem to apply – the generated `IntegerLit`s are all close to 0 although the customer generator should generate only numbers close to `2^64` or close to `-(2^64)`.

Admittedly I'm not even sure whether `IntegerLit` is a "container" or not – I'm not familiar with this term.

Eventually I'd also like to use custom generators for some non-unary constructors, although I can probably get away with plugging in a custom generator for `Text`.

**Comment by Lysxia** [comment]
There is currently no way to override a constructor specifically, but I can definitely add such a feature.

Another idea is to use a "generic surgery". [There's a way described in generic-data and using generic-lens](https://hackage.haskell.org/package/generic-data-0.7.0.0/docs/Generic-Data-Microsurgery.html#g:1) which should work with prisms too, without any modification to any of the libraries involved, but I haven't tried yet. Roughly, the idea is to modify the `Generic` instance of your data type to wrap the `IntegerLit` constructor in some newtype with a custom `Arbitrary` instance.

"container" isn't a standard term, I'll try to explain that better in the docs, thanks for bringing it up! If you have a `Gen1_ F` in your custom generators, then any field with some type `F a` will use that generator instead of the `Arbitrary` instance for `F a` (if it even exists). So in your case, `Gen1_ (Expr s)` overrides all `Expr s a` fields, in other words, the toplevel generator is no longer recursive:  `genericArbitrary*` picks a constructor, and any `Expr` field gets filled with `IntegerLit`.

**Comment by sjakobi** [comment]
> There is currently no way to override a constructor specifically, but I can definitely add such a feature.
> 
> Another idea is to use a "generic surgery". [There's a way described in generic-data and using generic-lens](https://hackage.haskell.org/package/generic-data-0.7.0.0/docs/Generic-Data-Microsurgery.html#g:1) which should work with prisms too, without any modification to any of the libraries involved, but I haven't tried yet. Roughly, the idea is to modify the `Generic` instance of your data type to wrap the `IntegerLit` constructor in some newtype with a custom `Arbitrary` instance.

"Generic surgery" looks neat, but I'm rather hesitant to bring more complexity into this testsuite – I'm afraid that it would discourage contributors from keeping it up to date. `dhall` also tries pretty hard to stay compatible with GHC-7.10.3 (for Eta) which makes adding new dependencies tricky.

So if you could add that feature, that would be super cool! :)

> If you have a `Gen1_ F` in your custom generators, then any field with some type `F a` will use that generator instead of the `Arbitrary` instance for `F a` (if it even exists). So in your case, `Gen1_ (Expr s)` overrides all `Expr s a` fields, in other words, the toplevel generator is no longer recursive: `genericArbitrary*` picks a constructor, and any `Expr` field gets filled with `IntegerLit`.

That's a bit strange because the `Expr`s I'm seeing are not all `IntegerLit`s, nor are all fields of other `Expr` constructors filled with `IntegerLit`s. It appears to me that the `customGens` have no affect at all!

**Comment by sjakobi** [comment]
customGens :: Gen Integer :+ ()
        customGens = integer :+ ()

This `customeGens` OTOH does cause all `Integer` fields fields to be generated from `integer`! :+1:

**Comment by Lysxia** [comment]
> dhall also tries pretty hard to stay compatible with GHC-7.10.3 (for Eta)

That makes things awkward because the names of constructor of generic types as `Symbol`s are only available since 8.0. We could always refer to constructors by position, although that's a little more fragile.

> That's a bit strange because the Exprs I'm seeing are not all IntegerLits, nor are all fields of other Expr constructors filled with IntegerLits. It appears to me that the customGens have no affect at all!

Oh. The thing I missed is that `ScopedTypeVariables` *not* enabled, so [it's not the same `s` on lines 168 and 174](https://github.com/dhall-lang/dhall-haskell/blob/b0e622adc144489d329f5b6b27df4f91560900c0/dhall/tests/Dhall/Test/QuickCheck.hs#L168-L175). That's why the custom generator does nothing. It's quite a brittle mechanism.

**Comment by sjakobi** [comment]
> > dhall also tries pretty hard to stay compatible with GHC-7.10.3 (for Eta)
> 
> That makes things awkward because the names of constructor of generic types as `Symbol`s are only available since 8.0. We could always refer to constructors by position, although that's a little more fragile.

[I can just default to `uniform` for `GHC-7.10`.](https://github.com/dhall-lang/dhall-haskell/pull/1282/commits/15df268fd86450be562857dc48d3733a058e9164)

> The thing I missed is that `ScopedTypeVariables` _not_ enabled, so [it's not the same `s` on lines 168 and 174](https://github.com/dhall-lang/dhall-haskell/blob/b0e622adc144489d329f5b6b27df4f91560900c0/dhall/tests/Dhall/Test/QuickCheck.hs#L168-L175). That's why the custom generator does nothing. It's quite a brittle mechanism.

Oh, I don't think I could have figured that out! :+1:

**Comment by Lysxia** [comment]
> I can just default to uniform for GHC-7.10.

Would it be a good idea to make it so that you can annotate the weights regardless of the GHC version (as long as `Symbol` is a thing), but they just won't be checked on 7.10 and older versions?

**Comment by sjakobi** [comment]
IMHO it's not very important for dhall that the tests are equally powerful with GHC-7.10 as with more recent GHC versions. Eventually we'll be able to stop supporting 7.10 anyway!

Also, this sounds like it would also be a rather dangerous feature – if you don't check with >= GHC-8.0, you might misattribute the weights!

**Comment by sjakobi** [comment]
I just realized that, as a workaround, I can use `oneof` or `frequency` to combine a generic generator with a custom one. I guess, a solution integrated in `generic-random` would still be nice, but that alternative should also work.

**Comment by Lysxia** [comment]
I just released [generic-random 1.3.0.0](https://hackage.haskell.org/package/generic-random-1.3.0.0)!

**Comment by sjakobi** [comment]
Thank you for the great support @Lysxia! :)
